package com.eventplatform.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;
import jakarta.persistence.OneToOne;
import jakarta.persistence.JoinColumn;
import java.time.LocalDateTime;

// @Entity: Maps this Java class to the "payments" database table.
@Entity
@Table(name = "payments")
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The unique order ID generated by the Razorpay backend API.
    // - unique = true: No two payments can refer to the same Razorpay order ID.
    // - nullable = false: A payment record must always have a reference order ID.
    @Column(name = "razorpay_order_id", unique = true, nullable = false)
    private String razorpayOrderId;

    // The transaction payment ID returned by Razorpay after successful payment deduction.
    // - nullable = true: Will be null initially when the order is created, and updated on success.
    // - unique = true: No two transactions can have the same payment ID.
    @Column(name = "razorpay_payment_id", unique = true)
    private String razorpayPaymentId;

    // The signature generated by Razorpay to verify the payment integrity (hash signature verification).
    @Column(name = "razorpay_signature")
    private String razorpaySignature;

    // Transaction amount in Rupees. Cannot be empty.
    @Column(name = "amount", nullable = false)
    private Double amount;

    // Payment transaction status:
    // - PENDING: Order created but payment not completed.
    // - SUCCESS: Payment signature verified and transaction approved.
    // - FAILED: Transaction failed/rejected by payment gateway.
    @Column(name = "status", nullable = false)
    private String status;

    // Timestamp when the payment status was updated.
    @Column(name = "payment_date")
    private LocalDateTime paymentDate;

    // @OneToOne: Establishes a One-to-One relationship with Registration.
    // - Each payment corresponds to exactly one event registration.
    // - @JoinColumn(name = "registration_id", unique = true, nullable = false):
    //   Creates a foreign key column named 'registration_id' inside the payments table.
    //   - unique = true: Enforces that a registration ID can only be paid for once (prevents duplicate payment records for the same registration).
    //   - nullable = false: Every payment record must be linked to a registration.
    @OneToOne
    @JoinColumn(name = "registration_id", unique = true, nullable = false)
    private Registration registration;

    // Default Constructor: Required by JPA/Hibernate.
    public Payment() {
    }

    // Parameterized Constructor: Helper for payment initiation.
    public Payment(String razorpayOrderId, Double amount, String status, Registration registration) {
        this.razorpayOrderId = razorpayOrderId;
        this.amount = amount;
        this.status = status;
        this.registration = registration;
    }

    // Getters and Setters:
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRazorpayOrderId() {
        return razorpayOrderId;
    }

    public void setRazorpayOrderId(String razorpayOrderId) {
        this.razorpayOrderId = razorpayOrderId;
    }

    public String getRazorpayPaymentId() {
        return razorpayPaymentId;
    }

    public void setRazorpayPaymentId(String razorpayPaymentId) {
        this.razorpayPaymentId = razorpayPaymentId;
    }

    public String getRazorpaySignature() {
        return razorpaySignature;
    }

    public void setRazorpaySignature(String razorpaySignature) {
        this.razorpaySignature = razorpaySignature;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(LocalDateTime paymentDate) {
        this.paymentDate = paymentDate;
    }

    public Registration getRegistration() {
        return registration;
    }

    public void setRegistration(Registration registration) {
        this.registration = registration;
    }
}
