package com.eventplatform.dto;

import java.util.List;

// DTO representing the authentication response containing the JWT token and basic user details.
// Returning basic profile information along with the token helps the frontend instantly know
// who is logged in and what roles they have (without needing to decode the JWT string on the client side).
public class AuthResponse {

    // The JWT access token generated by the server.
    private String accessToken;

    // The type of the token, typically "Bearer".
    private String tokenType = "Bearer";

    // User profile email.
    private String email;

    // User profile display name.
    private String name;

    // List of roles assigned to the user (e.g., ["ROLE_USER"]).
    private List<String> roles;

    // Default Constructor: Required for JSON mapping.
    public AuthResponse() {
    }

    // Parameterized Constructor:
    public AuthResponse(String accessToken, String email, String name, List<String> roles) {
        this.accessToken = accessToken;
        this.email = email;
        this.name = name;
        this.roles = roles;
    }

    // Getters and Setters:
    
    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getTokenType() {
        return tokenType;
    }

    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<String> getRoles() {
        return roles;
    }

    public void setRoles(List<String> roles) {
        this.roles = roles;
    }
}
