package com.eventplatform.dto;

// DTO to capture the transaction callback parameters returned by the Razorpay Checkout form.
// Once a user finishes payment on the frontend, Razorpay sends back three unique identifiers.
// The frontend packs them in this object and posts them to our verification endpoint.
public class PaymentRequest {

    // The unique ID representing this specific order, created on the Razorpay server.
    private String razorpayOrderId;

    // The unique ID representing the successful transaction instance, created by Razorpay.
    private String razorpayPaymentId;

    // A cryptographic signature generated by Razorpay.
    // We recreate this signature on the server using our key-secret and compare them to verify the payment's legitimacy.
    private String razorpaySignature;

    // Default Constructor: Required for JSON deserialization
    public PaymentRequest() {
    }

    // Parameterized Constructor:
    public PaymentRequest(String razorpayOrderId, String razorpayPaymentId, String razorpaySignature) {
        this.razorpayOrderId = razorpayOrderId;
        this.razorpayPaymentId = razorpayPaymentId;
        this.razorpaySignature = razorpaySignature;
    }

    // Getters and Setters:
    
    public String getRazorpayOrderId() {
        return razorpayOrderId;
    }

    public void setRazorpayOrderId(String razorpayOrderId) {
        this.razorpayOrderId = razorpayOrderId;
    }

    public String getRazorpayPaymentId() {
        return razorpayPaymentId;
    }

    public void setRazorpayPaymentId(String razorpayPaymentId) {
        this.razorpayPaymentId = razorpayPaymentId;
    }

    public String getRazorpaySignature() {
        return razorpaySignature;
    }

    public void setRazorpaySignature(String razorpaySignature) {
        this.razorpaySignature = razorpaySignature;
    }
}
